"""Discovery-only MCP metadata helpers for PyProcore."""

from pyprocore.mcp.capabilities import build_mcp_capability_summary, build_mcp_tool_summary
from pyprocore.mcp.compatibility import (
    McpCompatibilityReport,
    McpCompatibilityStatus,
    build_mcp_compatibility_report,
    mcp_compatibility_report_to_json,
    mcp_compatibility_report_to_markdown,
    sample_mcp_compatibility_report,
    write_mcp_compatibility_report,
)
from pyprocore.mcp.contracts import (
    McpContractFinding,
    McpContractValidationResult,
    McpDisabledExecutionResponse,
    McpDiscoveryContract,
    McpSampleRequest,
    McpSampleResponse,
    build_mcp_contract_report,
    validate_mcp_capability_summary,
    validate_mcp_contracts,
    validate_mcp_disabled_execution_contract,
    validate_mcp_discovery_manifest,
    validate_mcp_prompt_manifest,
    validate_mcp_resource_manifest,
)
from pyprocore.mcp.discovery import (
    build_mcp_discovery_manifest,
    build_mcp_resource_templates,
    build_mcp_server_info,
    build_mcp_stdio_discovery_payload,
    build_mcp_tool_definitions,
    mcp_manifest_to_json,
)
from pyprocore.mcp.models import (
    McpCapabilitySummary,
    McpDiscoveryManifest,
    McpPrompt,
    McpPromptArgument,
    McpPromptKind,
    McpResource,
    McpResourceKind,
    McpResourceTemplate,
    McpSafetyBoundary,
    McpServerInfo,
    McpToolSummary,
)
from pyprocore.mcp.prompts import get_mcp_prompt, list_mcp_prompts, safe_mcp_prompt_not_found
from pyprocore.mcp.resources import (
    disabled_mcp_execution_response,
    get_mcp_resource,
    list_mcp_resources,
    read_mcp_resource_payload,
    safe_mcp_resource_not_found,
)
from pyprocore.mcp.snapshots import (
    McpDiscoverySnapshot,
    McpSnapshotMetadata,
    build_mcp_discovery_snapshot,
    compare_mcp_discovery_snapshots,
    load_mcp_discovery_snapshot,
    mcp_snapshot_to_json,
    summarize_mcp_discovery_snapshot,
    write_mcp_discovery_snapshot,
)

__all__ = [
    "McpCapabilitySummary",
    "McpCompatibilityReport",
    "McpCompatibilityStatus",
    "McpContractFinding",
    "McpContractValidationResult",
    "McpDisabledExecutionResponse",
    "McpDiscoveryManifest",
    "McpDiscoveryContract",
    "McpDiscoverySnapshot",
    "McpPrompt",
    "McpPromptArgument",
    "McpPromptKind",
    "McpResource",
    "McpResourceKind",
    "McpResourceTemplate",
    "McpSafetyBoundary",
    "McpSampleRequest",
    "McpSampleResponse",
    "McpServerInfo",
    "McpSnapshotMetadata",
    "McpToolSummary",
    "build_mcp_compatibility_report",
    "build_mcp_capability_summary",
    "build_mcp_contract_report",
    "build_mcp_discovery_manifest",
    "build_mcp_discovery_snapshot",
    "build_mcp_resource_templates",
    "build_mcp_server_info",
    "build_mcp_stdio_discovery_payload",
    "build_mcp_tool_definitions",
    "build_mcp_tool_summary",
    "compare_mcp_discovery_snapshots",
    "disabled_mcp_execution_response",
    "get_mcp_prompt",
    "get_mcp_resource",
    "list_mcp_prompts",
    "list_mcp_resources",
    "load_mcp_discovery_snapshot",
    "mcp_compatibility_report_to_json",
    "mcp_compatibility_report_to_markdown",
    "mcp_manifest_to_json",
    "mcp_snapshot_to_json",
    "read_mcp_resource_payload",
    "safe_mcp_prompt_not_found",
    "safe_mcp_resource_not_found",
    "sample_mcp_compatibility_report",
    "summarize_mcp_discovery_snapshot",
    "validate_mcp_capability_summary",
    "validate_mcp_contracts",
    "validate_mcp_disabled_execution_contract",
    "validate_mcp_discovery_manifest",
    "validate_mcp_prompt_manifest",
    "validate_mcp_resource_manifest",
    "write_mcp_compatibility_report",
    "write_mcp_discovery_snapshot",
]
