"""Typed response models for Procore resources."""

from pyprocore.models.base import ProcoreModel
from pyprocore.models.resources import (
    RFI,
    Attachment,
    Company,
    DailyLogCount,
    DailyLogEntry,
    DailyLogHeader,
    DailyLogsByType,
    DelayLogType,
    Document,
    DocumentFolder,
    Drawing,
    DrawingArea,
    DrawingDiscipline,
    PhotoAlbum,
    PhotoAlbumDownloadResult,
    PhotoImage,
    Project,
    RFIQuestion,
    SpecificationRevisionDownload,
    SpecificationSection,
    SpecificationSectionRevision,
    SpecificationSet,
    Status,
    Submittal,
    User,
)

__all__ = [
    "Attachment",
    "Company",
    "DailyLogCount",
    "DailyLogEntry",
    "DailyLogHeader",
    "DailyLogsByType",
    "DelayLogType",
    "Document",
    "DocumentFolder",
    "Drawing",
    "DrawingArea",
    "DrawingDiscipline",
    "PhotoAlbum",
    "PhotoAlbumDownloadResult",
    "PhotoImage",
    "ProcoreModel",
    "Project",
    "RFI",
    "RFIQuestion",
    "SpecificationRevisionDownload",
    "SpecificationSection",
    "SpecificationSectionRevision",
    "SpecificationSet",
    "Status",
    "Submittal",
    "User",
]
