"""Local-only API maintenance assistant for user-provided OAS JSON files."""

from pyprocore.maintenance.codebase import scan_pyprocore_usage
from pyprocore.maintenance.coverage import analyze_pyprocore_coverage_gaps
from pyprocore.maintenance.drift import (
    compare_oas_catalogs,
    detect_added_endpoints,
    detect_changed_methods,
    detect_changed_operation_ids,
    detect_changed_parameters,
    detect_removed_endpoints,
    detect_risky_changes,
)
from pyprocore.maintenance.impact import analyze_codebase_api_impact
from pyprocore.maintenance.impact_reports import (
    api_impact_report_to_json,
    api_impact_report_to_markdown,
    codebase_scan_report_to_json,
    codebase_scan_report_to_markdown,
)
from pyprocore.maintenance.migration import build_migration_patch_plan
from pyprocore.maintenance.models import (
    MAINTENANCE_MODE,
    MAINTENANCE_SCHEMA_VERSION,
    ApiCoverageGap,
    ApiCoverageGapReport,
    ApiDriftReport,
    ApiEndpointChange,
    ApiImpactFinding,
    ApiImpactReport,
    ApiMaintenanceFinding,
    ApiMaintenancePlan,
    ApiMaintenanceTask,
    ApiScaffoldCopyResult,
    ApiScaffoldFile,
    ApiScaffoldPlan,
    CodebaseFileFinding,
    CodebaseScanOptions,
    CodebaseScanReport,
    ImpactedUsage,
    MigrationPatchArtifact,
    MigrationPatchFile,
    MigrationPatchHunk,
    MigrationPatchPlan,
    MigrationPatchPlanOptions,
    MigrationPatchReport,
    MigrationPatchSuggestion,
    MigrationSafetyFinding,
    MigrationSuggestion,
    PullRequestDraftArtifact,
    PullRequestDraftChecklistItem,
    PullRequestDraftOptions,
    PullRequestDraftPack,
    PullRequestDraftReport,
    PullRequestDraftRiskSummary,
    PullRequestDraftSection,
    PyprocoreCallUsage,
    PyprocoreCliUsage,
    PyprocoreImportUsage,
    PyprocoreUsage,
)
from pyprocore.maintenance.patch_plan import (
    render_unified_diff_suggestion,
    write_migration_patch_artifacts,
)
from pyprocore.maintenance.patch_reports import (
    build_migration_patch_artifacts,
    manual_review_checklist_to_markdown,
    migration_patch_plan_to_json,
    migration_patch_plan_to_markdown,
    migration_patch_report_to_json,
    migration_patch_report_to_markdown,
)
from pyprocore.maintenance.plans import build_api_maintenance_plan
from pyprocore.maintenance.pr_draft import build_pr_draft_pack, write_pr_draft_pack
from pyprocore.maintenance.pr_reports import (
    build_pr_draft_artifacts,
    pr_draft_pack_to_json,
    pr_draft_pack_to_markdown,
    pr_draft_report_to_json,
    pr_draft_report_to_markdown,
    pr_review_checklist_to_markdown,
    pr_risk_summary_to_markdown,
    pr_test_plan_to_markdown,
)
from pyprocore.maintenance.reports import (
    coverage_gap_report_to_markdown,
    drift_report_to_markdown,
    maintenance_plan_to_markdown,
    maintenance_report_to_json,
    scaffold_copy_result_to_markdown,
    scaffold_plan_to_markdown,
)
from pyprocore.maintenance.scaffold import (
    copy_read_only_endpoint_scaffold,
    plan_read_only_endpoint_scaffold,
)

__all__ = [
    "MAINTENANCE_MODE",
    "MAINTENANCE_SCHEMA_VERSION",
    "ApiCoverageGap",
    "ApiCoverageGapReport",
    "ApiDriftReport",
    "ApiEndpointChange",
    "ApiImpactFinding",
    "ApiImpactReport",
    "ApiMaintenanceFinding",
    "ApiMaintenancePlan",
    "ApiMaintenanceTask",
    "ApiScaffoldCopyResult",
    "ApiScaffoldFile",
    "ApiScaffoldPlan",
    "CodebaseFileFinding",
    "CodebaseScanOptions",
    "CodebaseScanReport",
    "ImpactedUsage",
    "MigrationSuggestion",
    "MigrationPatchArtifact",
    "MigrationPatchFile",
    "MigrationPatchHunk",
    "MigrationPatchPlan",
    "MigrationPatchPlanOptions",
    "MigrationPatchReport",
    "MigrationPatchSuggestion",
    "MigrationSafetyFinding",
    "PullRequestDraftArtifact",
    "PullRequestDraftChecklistItem",
    "PullRequestDraftOptions",
    "PullRequestDraftPack",
    "PullRequestDraftReport",
    "PullRequestDraftRiskSummary",
    "PullRequestDraftSection",
    "PyprocoreCallUsage",
    "PyprocoreCliUsage",
    "PyprocoreImportUsage",
    "PyprocoreUsage",
    "analyze_codebase_api_impact",
    "analyze_pyprocore_coverage_gaps",
    "build_api_maintenance_plan",
    "build_migration_patch_artifacts",
    "build_migration_patch_plan",
    "build_pr_draft_artifacts",
    "build_pr_draft_pack",
    "compare_oas_catalogs",
    "copy_read_only_endpoint_scaffold",
    "coverage_gap_report_to_markdown",
    "api_impact_report_to_json",
    "api_impact_report_to_markdown",
    "codebase_scan_report_to_json",
    "codebase_scan_report_to_markdown",
    "detect_added_endpoints",
    "detect_changed_methods",
    "detect_changed_operation_ids",
    "detect_changed_parameters",
    "detect_removed_endpoints",
    "detect_risky_changes",
    "drift_report_to_markdown",
    "maintenance_plan_to_markdown",
    "maintenance_report_to_json",
    "manual_review_checklist_to_markdown",
    "migration_patch_plan_to_json",
    "migration_patch_plan_to_markdown",
    "migration_patch_report_to_json",
    "migration_patch_report_to_markdown",
    "pr_draft_pack_to_json",
    "pr_draft_pack_to_markdown",
    "pr_draft_report_to_json",
    "pr_draft_report_to_markdown",
    "pr_review_checklist_to_markdown",
    "pr_risk_summary_to_markdown",
    "pr_test_plan_to_markdown",
    "plan_read_only_endpoint_scaffold",
    "scaffold_copy_result_to_markdown",
    "scaffold_plan_to_markdown",
    "scan_pyprocore_usage",
    "render_unified_diff_suggestion",
    "write_migration_patch_artifacts",
    "write_pr_draft_pack",
]
