"""Metadata-only plugin architecture foundation for PyProcore.

Phase 11A plugin helpers validate and expose safe plugin manifests. They do not
install plugins, fetch remote registries, import arbitrary plugin modules, or
execute plugin code.
"""

from pyprocore.plugins.builtin_hooks import (
    build_basic_quality_report,
    builtin_hook_metadata,
    builtin_hook_registrations,
    builtin_hook_registry,
    export_records_to_jsonl_payload,
    format_records_as_summary,
    transform_records_select_fields,
    validate_no_empty_ids,
    validate_required_fields,
)
from pyprocore.plugins.discovery import (
    builtin_plugin_manifests,
    discover_builtin_plugins,
    discover_installed_plugin_metadata,
    discover_local_plugin_manifests,
    discover_plugins,
    load_local_plugin_manifest_file,
)
from pyprocore.plugins.hook_registry import (
    PluginHookRegistry,
    export_hook_registry_manifest,
    find_hooks_by_type,
    get_hook,
    list_hooks,
    register_hook,
    run_exporter_hook,
    run_formatter_hook,
    run_record_transformer_hook,
    run_validator_hook,
    unregister_hook,
    validate_hook_registration,
)
from pyprocore.plugins.hooks import (
    PluginHookCallable,
    PluginHookContext,
    PluginHookMetadata,
    PluginHookRegistration,
    PluginHookRegistryManifest,
    PluginHookResult,
    PluginHookType,
    redact_sensitive_text,
    sanitize_hook_value,
)
from pyprocore.plugins.models import (
    PLUGIN_SCHEMA_VERSION,
    PluginCapability,
    PluginDiscoveryResult,
    PluginManifest,
    PluginManifestData,
    PluginMetadata,
    PluginRegistration,
    PluginRegistryManifest,
    PluginSafetyLevel,
    PluginValidationResult,
)
from pyprocore.plugins.registry import (
    PluginRegistry,
    export_plugin_registry_manifest,
    find_plugins_by_capability,
    get_plugin,
    list_plugins,
    register_plugin_manifest,
    unregister_plugin,
)
from pyprocore.plugins.validation import (
    load_plugin_manifest_from_dict,
    validate_plugin_manifest,
    validate_plugin_manifest_data,
)

__all__ = [
    "PLUGIN_SCHEMA_VERSION",
    "PluginCapability",
    "PluginDiscoveryResult",
    "PluginManifest",
    "PluginManifestData",
    "PluginMetadata",
    "PluginRegistration",
    "PluginRegistry",
    "PluginRegistryManifest",
    "PluginSafetyLevel",
    "PluginValidationResult",
    "builtin_plugin_manifests",
    "discover_builtin_plugins",
    "discover_installed_plugin_metadata",
    "discover_local_plugin_manifests",
    "discover_plugins",
    "export_plugin_registry_manifest",
    "find_plugins_by_capability",
    "get_plugin",
    "list_plugins",
    "load_local_plugin_manifest_file",
    "load_plugin_manifest_from_dict",
    "register_plugin_manifest",
    "unregister_plugin",
    "validate_plugin_manifest",
    "validate_plugin_manifest_data",
    "PluginHookCallable",
    "PluginHookContext",
    "PluginHookMetadata",
    "PluginHookRegistration",
    "PluginHookRegistry",
    "PluginHookRegistryManifest",
    "PluginHookResult",
    "PluginHookType",
    "build_basic_quality_report",
    "builtin_hook_metadata",
    "builtin_hook_registry",
    "builtin_hook_registrations",
    "export_hook_registry_manifest",
    "export_records_to_jsonl_payload",
    "find_hooks_by_type",
    "format_records_as_summary",
    "get_hook",
    "list_hooks",
    "redact_sensitive_text",
    "register_hook",
    "run_exporter_hook",
    "run_formatter_hook",
    "run_record_transformer_hook",
    "run_validator_hook",
    "sanitize_hook_value",
    "transform_records_select_fields",
    "unregister_hook",
    "validate_hook_registration",
    "validate_no_empty_ids",
    "validate_required_fields",
]
