"""Safe local DMSA connection-profile planning helpers."""

from pyprocore.dmsa.checklists import (
    build_dmsa_permission_checklist,
    build_dmsa_smoke_check_plan,
)
from pyprocore.dmsa.diagnostics import diagnose_dmsa_permission_issue
from pyprocore.dmsa.models import (
    DmsaConnectionProfile,
    DmsaConnectionProfileInput,
    DmsaConnectionProfileValidationFinding,
    DmsaConnectionProfileValidationReport,
    DmsaConnectionSummary,
    DmsaInstallationPacket,
    DmsaPermissionChecklist,
    DmsaPermissionChecklistItem,
    DmsaPermissionDiagnosticFinding,
    DmsaPermissionDiagnosticReport,
    DmsaSmokeCheckItem,
    DmsaSmokeCheckPlan,
    DmsaSmokeCheckResult,
)
from pyprocore.dmsa.profiles import (
    build_dmsa_connection_profile,
    load_dmsa_connection_profile,
    redact_dmsa_connection_profile,
    settings_from_dmsa_connection_profile,
    summarize_dmsa_connection_profile,
    validate_dmsa_connection_profile,
    write_dmsa_connection_profile_template,
)
from pyprocore.dmsa.reports import (
    build_dmsa_installation_packet,
    dmsa_connection_summary_to_markdown,
    dmsa_installation_packet_to_markdown,
    dmsa_permission_checklist_to_markdown,
    dmsa_permission_diagnostic_to_markdown,
    dmsa_report_to_json,
    dmsa_smoke_check_plan_to_markdown,
    dmsa_validation_report_to_markdown,
)

__all__ = [
    "DmsaConnectionProfile",
    "DmsaConnectionProfileInput",
    "DmsaConnectionProfileValidationFinding",
    "DmsaConnectionProfileValidationReport",
    "DmsaConnectionSummary",
    "DmsaInstallationPacket",
    "DmsaPermissionChecklist",
    "DmsaPermissionChecklistItem",
    "DmsaPermissionDiagnosticFinding",
    "DmsaPermissionDiagnosticReport",
    "DmsaSmokeCheckItem",
    "DmsaSmokeCheckPlan",
    "DmsaSmokeCheckResult",
    "build_dmsa_connection_profile",
    "build_dmsa_installation_packet",
    "build_dmsa_permission_checklist",
    "build_dmsa_smoke_check_plan",
    "diagnose_dmsa_permission_issue",
    "dmsa_connection_summary_to_markdown",
    "dmsa_installation_packet_to_markdown",
    "dmsa_permission_checklist_to_markdown",
    "dmsa_permission_diagnostic_to_markdown",
    "dmsa_report_to_json",
    "dmsa_smoke_check_plan_to_markdown",
    "dmsa_validation_report_to_markdown",
    "load_dmsa_connection_profile",
    "redact_dmsa_connection_profile",
    "settings_from_dmsa_connection_profile",
    "summarize_dmsa_connection_profile",
    "validate_dmsa_connection_profile",
    "write_dmsa_connection_profile_template",
]
