"""Python SDK for the Procore REST API."""

from pyprocore.automation import (
    AutomationInput,
    DownloadedFile,
    WorkflowPackage,
    build_rfi_package,
    build_submittal_package,
    build_workflow_package,
)
from pyprocore.client import Procore
from pyprocore.core.exceptions import DuplicateMatchError, MultipleResultsError, NotFoundError
from pyprocore.services.photos import (
    download_photo,
    download_photo_album,
    find_photo,
    find_photo_album,
    get_photo,
    get_photo_album,
    list_photo_albums,
    list_photos,
)
from pyprocore.services.search import (
    find_company,
    find_document,
    find_document_folder,
    find_drawing,
    find_drawings_contains,
    find_project,
    find_project_contains,
    find_rfi,
    find_submittal,
)
from pyprocore.services.specifications import (
    download_specification_section_revision,
    find_specification_section,
    get_specification_section,
    get_specification_section_revision,
    list_specification_section_revisions,
    list_specification_sections,
    list_specification_sets,
)
from pyprocore.workflows import (
    ProjectSyncResult,
    SyncResult,
    export_rfis_to_csv,
    export_rfis_to_jsonl,
    export_submittals_to_csv,
    export_submittals_to_jsonl,
    sync_documents_to_folder,
    sync_project_to_folder,
    sync_rfis_to_folder,
    sync_submittals_to_folder,
)

__version__ = "2.0.0"

__all__ = [
    "AutomationInput",
    "DuplicateMatchError",
    "DownloadedFile",
    "MultipleResultsError",
    "NotFoundError",
    "Procore",
    "ProjectSyncResult",
    "SyncResult",
    "WorkflowPackage",
    "__version__",
    "build_rfi_package",
    "build_submittal_package",
    "build_workflow_package",
    "export_rfis_to_csv",
    "export_rfis_to_jsonl",
    "export_submittals_to_csv",
    "export_submittals_to_jsonl",
    "download_photo",
    "download_photo_album",
    "find_company",
    "find_document",
    "find_document_folder",
    "find_drawing",
    "find_drawings_contains",
    "find_photo",
    "find_photo_album",
    "find_project",
    "find_project_contains",
    "find_rfi",
    "find_specification_section",
    "find_submittal",
    "download_specification_section_revision",
    "get_photo",
    "get_photo_album",
    "get_specification_section",
    "get_specification_section_revision",
    "list_specification_section_revisions",
    "list_photo_albums",
    "list_photos",
    "list_specification_sections",
    "list_specification_sets",
    "sync_project_to_folder",
    "sync_documents_to_folder",
    "sync_rfis_to_folder",
    "sync_submittals_to_folder",
]
